### ISSUE TITLE
Freeze of mouse and keyboard

### ISSUE THREAD

**Issue by pdcurtis** [jaszhix/icingmenu#1]
If this issue is a bug report, please list your: 

  - Cinnamon version 3.2.7
  - Extension version 1.0.1
  - Linux distribution Mint 18.1

  - Theme was Void when this occurred and both original and icing menu installed at time

  - Output of cat ~/.cinnamon/configs/IcingTaskManager@json/*.json ???

I think you meant cat ~/.cinnamon/configs/IcingMenu@json/*.json which had gone by the time I got to write the issue up.

  - Describe the bug.

I added the icingmenu from Cinnamon Spices and initially everything seemed to be working fine and I could use both menus for comparison under a standard theme. Tried changing width and it seemed to ineffective and very slow and shortly after the mouse did nothing nor keyboard keys other than Ctrl Alt Backspace which got me to a login. After logging back in there was no panel but Ctrl Alt Backspace got me back once more to login screen and hence to Restart which restored panel and enabled me to remove the Applet but without any diagnostics from Looking Glass. Icing Task manager also loaded plus some of my own well tested Applets.

The most significant thing seems to be the slowing of changing width in Settings before the freeze. CPU use seemed normal even when changing width and when frozen. Sorry not to be able to be more helpful but I need the machine whilst away!
 
A useful start and I hope you get it fixed.

**Comment by jaszhix** [comment]
This sounds like a bug that was fixed in 1.0.1. Sorry some of the issue template info was copied from another applet project. Would you be able to pastebin the output of your ~/.xsession-errors or ~/.cinnamon/glass.log after this happens again?

**Comment by jaszhix** [comment]
@pdcurtis I'm not able to reproduce this one.

**Comment by pdcurtis** [comment]
Sorry, should have closed long ago as no further occurrences.
